### ISSUE TITLE
Only support the wav,16000Hz and 48000Hz?

### ISSUE THREAD

**Issue by wuqiangch** [FragJage/SpeakerVoiceIdentifier#2]
Only support the wav,16000Hz and 48000Hz? I take some my wav files which is 44100Hz。The result is wrong. Only the first person  can be classified correctly?

**Comment by FragJage** [comment]
I have not tested 44100Hz, but you can modify main.cpp line 9 to #define FREQ 44100. If the result is always false, you can increase TRAINSIZE and RECOGSIZE line 10 and 12. Be careful, the file must be large enough.
