### ISSUE TITLE
the vector need header file #include<vector>

### ISSUE THREAD

**Issue by dfowl** [FragJage/SpeakerVoiceIdentifier#4]

**Comment by FragJage** [comment]
Thank, there is already header file #include<vector> in mfcc.h and gmm.h.
Where do you have this issue ?

**Comment by dfowl** [comment]
Thanks,but,I don't know why!When  I use vs2017 to run it, it has a mistake that vector  is not defined.Now, I use vs2019 and it's ok???

**Comment by FragJage** [comment]
Ok, cool.
